export {default as Button} from './button/button.js'
export {default as Destino} from './destino/destino.js'
export {default as Costo} from './costo/costo.js'
export {default as Descripcion} from './descripcion/descripcion.js'
export {default as Actividades} from './actividades/actividades.js'
export {default as Duracionendias} from './duracionendias/duracionendias.js'